#############################################################################
# Makefile for building: Sorcery
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  Sorcery.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile Sorcery.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++14 -g -O2 -std=c++1y -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Sorcery1.0.0
DISTDIR = /u0/z234zhao/cs246/Sorcery/.tmp/Sorcery1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cc \
		canvas.cc \
		cardtemplate.cc \
		playercardtemplate.cc \
		centercardtemplate.cc \
		minioncardtemplate.cc \
		ascii_graphics.cc \
		Board.cc \
		Card.cc \
		Deck.cc \
		Enchantment.cc \
		Minion.cc \
		Player.cc \
		randomNum.cc \
		Ritual.cc \
		SorceryDex.cc \
		Spell.cc \
		Trigger.cc \
		Game.cc \
		miniontriggeredcardtemplate.cc \
		minionactivatedcardtemplate.cc \
		enchantmentcardtemplate.cc \
		enchantmentadcardtemplate.cc \
		spellcardtemplate.cc \
		ritualcardtemplate.cc moc_canvas.cpp \
		moc_cardtemplate.cc \
		moc_playercardtemplate.cc \
		moc_centercardtemplate.cc \
		moc_minioncardtemplate.cc \
		moc_miniontriggeredcardtemplate.cc \
		moc_minionactivatedcardtemplate.cc \
		moc_enchantmentcardtemplate.cc \
		moc_enchantmentadcardtemplate.cc \
		moc_spellcardtemplate.cc \
		moc_ritualcardtemplate.cc
OBJECTS       = main.o \
		canvas.o \
		cardtemplate.o \
		playercardtemplate.o \
		centercardtemplate.o \
		minioncardtemplate.o \
		ascii_graphics.o \
		Board.o \
		Card.o \
		Deck.o \
		Enchantment.o \
		Minion.o \
		Player.o \
		randomNum.o \
		Ritual.o \
		SorceryDex.o \
		Spell.o \
		Trigger.o \
		Game.o \
		miniontriggeredcardtemplate.o \
		minionactivatedcardtemplate.o \
		enchantmentcardtemplate.o \
		enchantmentadcardtemplate.o \
		spellcardtemplate.o \
		ritualcardtemplate.o \
		moc_canvas.o \
		moc_cardtemplate.o \
		moc_playercardtemplate.o \
		moc_centercardtemplate.o \
		moc_minioncardtemplate.o \
		moc_miniontriggeredcardtemplate.o \
		moc_minionactivatedcardtemplate.o \
		moc_enchantmentcardtemplate.o \
		moc_enchantmentadcardtemplate.o \
		moc_spellcardtemplate.o \
		moc_ritualcardtemplate.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++14.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Sorcery.pro canvas.h \
		cardtemplate.h \
		playercardtemplate.h \
		centercardtemplate.h \
		minioncardtemplate.h \
		ascii_graphics.h \
		Board.h \
		Card.h \
		CardType.h \
		Deck.h \
		Enchantment.h \
		Game.h \
		InvalidMoveException.h \
		Minion.h \
		Player.h \
		randomNum.h \
		Ritual.h \
		SorceryDex.h \
		Spell.h \
		Trigger.h \
		TriggerType.h \
		miniontriggeredcardtemplate.h \
		minionactivatedcardtemplate.h \
		enchantmentcardtemplate.h \
		enchantmentadcardtemplate.h \
		spellcardtemplate.h \
		ritualcardtemplate.h main.cc \
		canvas.cc \
		cardtemplate.cc \
		playercardtemplate.cc \
		centercardtemplate.cc \
		minioncardtemplate.cc \
		ascii_graphics.cc \
		Board.cc \
		Card.cc \
		Deck.cc \
		Enchantment.cc \
		Minion.cc \
		Player.cc \
		randomNum.cc \
		Ritual.cc \
		SorceryDex.cc \
		Spell.cc \
		Trigger.cc \
		Game.cc \
		miniontriggeredcardtemplate.cc \
		minionactivatedcardtemplate.cc \
		enchantmentcardtemplate.cc \
		enchantmentadcardtemplate.cc \
		spellcardtemplate.cc \
		ritualcardtemplate.cc
QMAKE_TARGET  = Sorcery
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = sorcery


first: all
####### Implicit rules

.SUFFIXES: .o .c .cc .cc .cxx .C

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Sorcery.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++14.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Sorcery.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++14.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
Sorcery.pro:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Sorcery.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents canvas.h cardtemplate.h playercardtemplate.h centercardtemplate.h minioncardtemplate.h ascii_graphics.h Board.h Card.h CardType.h Deck.h Enchantment.h Game.h InvalidMoveException.h Minion.h Player.h randomNum.h Ritual.h SorceryDex.h Spell.h Trigger.h TriggerType.h miniontriggeredcardtemplate.h minionactivatedcardtemplate.h enchantmentcardtemplate.h enchantmentadcardtemplate.h spellcardtemplate.h ritualcardtemplate.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cc canvas.cpp cardtemplate.cpp playercardtemplate.cpp centercardtemplate.cpp minioncardtemplate.cpp ascii_graphics.cc Board.cc Card.cc Deck.cc Enchantment.cc Minion.cc Player.cc randomNum.cc Ritual.cc SorceryDex.cc Spell.cc Trigger.cc Game.cc miniontriggeredcardtemplate.cpp minionactivatedcardtemplate.cpp enchantmentcardtemplate.cpp enchantmentadcardtemplate.cpp spellcardtemplate.cpp ritualcardtemplate.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_canvas.cc moc_cardtemplate.cpp moc_playercardtemplate.cpp moc_centercardtemplate.cpp moc_minioncardtemplate.cpp moc_miniontriggeredcardtemplate.cpp moc_minionactivatedcardtemplate.cpp moc_enchantmentcardtemplate.cpp moc_enchantmentadcardtemplate.cpp moc_spellcardtemplate.cpp moc_ritualcardtemplate.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_canvas.cc moc_cardtemplate.cpp moc_playercardtemplate.cpp moc_centercardtemplate.cpp moc_minioncardtemplate.cpp moc_miniontriggeredcardtemplate.cpp moc_minionactivatedcardtemplate.cpp moc_enchantmentcardtemplate.cpp moc_enchantmentadcardtemplate.cpp moc_spellcardtemplate.cpp moc_ritualcardtemplate.cpp
moc_canvas.cc: cardtemplate.h \
		playercardtemplate.h \
		Game.h \
		Player.h \
		Deck.h \
		Card.h \
		CardType.h \
		ascii_graphics.h \
		SorceryDex.h \
		Board.h \
		Minion.h \
		TriggerType.h \
		Ritual.h \
		Trigger.h \
		canvas.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/u0/z234zhao/cs246/Sorcery -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include canvas.h -o moc_canvas.cc

moc_cardtemplate.cc: cardtemplate.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/u0/z234zhao/cs246/Sorcery -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include cardtemplate.h -o moc_cardtemplate.cc

moc_playercardtemplate.cc: cardtemplate.h \
		playercardtemplate.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/u0/z234zhao/cs246/Sorcery -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include playercardtemplate.h -o moc_playercardtemplate.cc

moc_centercardtemplate.cc: cardtemplate.h \
		centercardtemplate.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/u0/z234zhao/cs246/Sorcery -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include centercardtemplate.h -o moc_centercardtemplate.cc

moc_minioncardtemplate.cc: cardtemplate.h \
		minioncardtemplate.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/u0/z234zhao/cs246/Sorcery -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include minioncardtemplate.h -o moc_minioncardtemplate.cc

moc_miniontriggeredcardtemplate.cc: cardtemplate.h \
		miniontriggeredcardtemplate.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/u0/z234zhao/cs246/Sorcery -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include miniontriggeredcardtemplate.h -o moc_miniontriggeredcardtemplate.cc

moc_minionactivatedcardtemplate.cc: cardtemplate.h \
		minionactivatedcardtemplate.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/u0/z234zhao/cs246/Sorcery -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include minionactivatedcardtemplate.h -o moc_minionactivatedcardtemplate.cc

moc_enchantmentcardtemplate.cc: cardtemplate.h \
		enchantmentcardtemplate.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/u0/z234zhao/cs246/Sorcery -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include enchantmentcardtemplate.h -o moc_enchantmentcardtemplate.cc

moc_enchantmentadcardtemplate.cc: cardtemplate.h \
		enchantmentadcardtemplate.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/u0/z234zhao/cs246/Sorcery -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include enchantmentadcardtemplate.h -o moc_enchantmentadcardtemplate.cc

moc_spellcardtemplate.cc: cardtemplate.h \
		spellcardtemplate.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/u0/z234zhao/cs246/Sorcery -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include spellcardtemplate.h -o moc_spellcardtemplate.cc

moc_ritualcardtemplate.cc: cardtemplate.h \
		ritualcardtemplate.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/u0/z234zhao/cs246/Sorcery -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ritualcardtemplate.h -o moc_ritualcardtemplate.cc

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cc Player.h \
		Deck.h \
		Card.h \
		CardType.h \
		ascii_graphics.h \
		cardtemplate.h \
		SorceryDex.h \
		Board.h \
		Minion.h \
		Game.h \
		Trigger.h \
		TriggerType.h \
		Ritual.h \
		InvalidMoveException.h \
		canvas.h \
		playercardtemplate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cc

canvas.o: canvas.cc canvas.h \
		cardtemplate.h \
		playercardtemplate.h \
		Game.h \
		Player.h \
		Deck.h \
		Card.h \
		CardType.h \
		ascii_graphics.h \
		SorceryDex.h \
		Board.h \
		Minion.h \
		TriggerType.h \
		Ritual.h \
		Trigger.h \
		centercardtemplate.h \
		minioncardtemplate.h \
		InvalidMoveException.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o canvas.o canvas.cc

cardtemplate.o: cardtemplate.cc cardtemplate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cardtemplate.o cardtemplate.cc

playercardtemplate.o: playercardtemplate.cc playercardtemplate.h \
		cardtemplate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o playercardtemplate.o playercardtemplate.cc

centercardtemplate.o: centercardtemplate.cc centercardtemplate.h \
		cardtemplate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o centercardtemplate.o centercardtemplate.cc

minioncardtemplate.o: minioncardtemplate.cc minioncardtemplate.h \
		cardtemplate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minioncardtemplate.o minioncardtemplate.cc

ascii_graphics.o: ascii_graphics.cc ascii_graphics.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ascii_graphics.o ascii_graphics.cc

Board.o: Board.cc ascii_graphics.h \
		Card.h \
		CardType.h \
		cardtemplate.h \
		Minion.h \
		Game.h \
		Player.h \
		Deck.h \
		SorceryDex.h \
		Board.h \
		TriggerType.h \
		Ritual.h \
		Trigger.h \
		Enchantment.h \
		Spell.h \
		InvalidMoveException.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Board.o Board.cc

Card.o: Card.cc Card.h \
		CardType.h \
		ascii_graphics.h \
		cardtemplate.h \
		Player.h \
		Deck.h \
		SorceryDex.h \
		Board.h \
		Minion.h \
		Game.h \
		Trigger.h \
		TriggerType.h \
		Ritual.h \
		Spell.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Card.o Card.cc

Deck.o: Deck.cc ascii_graphics.h \
		Deck.h \
		Card.h \
		CardType.h \
		cardtemplate.h \
		SorceryDex.h \
		Minion.h \
		Game.h \
		Player.h \
		Board.h \
		TriggerType.h \
		Ritual.h \
		Trigger.h \
		Enchantment.h \
		Spell.h \
		InvalidMoveException.h \
		randomNum.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Deck.o Deck.cc

Enchantment.o: Enchantment.cc Enchantment.h \
		Card.h \
		CardType.h \
		ascii_graphics.h \
		cardtemplate.h \
		Minion.h \
		Game.h \
		Player.h \
		Deck.h \
		SorceryDex.h \
		Board.h \
		TriggerType.h \
		Ritual.h \
		Trigger.h \
		Spell.h \
		InvalidMoveException.h \
		minioncardtemplate.h \
		minionactivatedcardtemplate.h \
		miniontriggeredcardtemplate.h \
		enchantmentadcardtemplate.h \
		enchantmentcardtemplate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Enchantment.o Enchantment.cc

Minion.o: Minion.cc Minion.h \
		Card.h \
		CardType.h \
		ascii_graphics.h \
		cardtemplate.h \
		Game.h \
		Player.h \
		Deck.h \
		SorceryDex.h \
		Board.h \
		TriggerType.h \
		Ritual.h \
		Trigger.h \
		InvalidMoveException.h \
		Enchantment.h \
		Spell.h \
		minioncardtemplate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Minion.o Minion.cc

Player.o: Player.cc Player.h \
		Deck.h \
		Card.h \
		CardType.h \
		ascii_graphics.h \
		cardtemplate.h \
		SorceryDex.h \
		Board.h \
		Minion.h \
		Game.h \
		Trigger.h \
		TriggerType.h \
		Ritual.h \
		InvalidMoveException.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Player.o Player.cc

randomNum.o: randomNum.cc randomNum.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o randomNum.o randomNum.cc

Ritual.o: Ritual.cc Ritual.h \
		Card.h \
		CardType.h \
		ascii_graphics.h \
		cardtemplate.h \
		Game.h \
		Player.h \
		Deck.h \
		SorceryDex.h \
		Board.h \
		Minion.h \
		TriggerType.h \
		Trigger.h \
		InvalidMoveException.h \
		ritualcardtemplate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Ritual.o Ritual.cc

SorceryDex.o: SorceryDex.cc SorceryDex.h \
		Card.h \
		CardType.h \
		ascii_graphics.h \
		cardtemplate.h \
		Spell.h \
		Game.h \
		Player.h \
		Deck.h \
		Board.h \
		Minion.h \
		TriggerType.h \
		Ritual.h \
		Trigger.h \
		Enchantment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SorceryDex.o SorceryDex.cc

Spell.o: Spell.cc Spell.h \
		Card.h \
		CardType.h \
		ascii_graphics.h \
		cardtemplate.h \
		Game.h \
		Player.h \
		Deck.h \
		SorceryDex.h \
		Board.h \
		Minion.h \
		TriggerType.h \
		Ritual.h \
		Trigger.h \
		InvalidMoveException.h \
		randomNum.h \
		spellcardtemplate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Spell.o Spell.cc

Trigger.o: Trigger.cc Trigger.h \
		Card.h \
		CardType.h \
		ascii_graphics.h \
		cardtemplate.h \
		TriggerType.h \
		Ritual.h \
		Game.h \
		Player.h \
		Deck.h \
		SorceryDex.h \
		Board.h \
		Minion.h \
		randomNum.h \
		InvalidMoveException.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Trigger.o Trigger.cc

Game.o: Game.cc Game.h \
		Player.h \
		Deck.h \
		Card.h \
		CardType.h \
		ascii_graphics.h \
		cardtemplate.h \
		SorceryDex.h \
		Board.h \
		Minion.h \
		TriggerType.h \
		Ritual.h \
		Trigger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Game.o Game.cc

miniontriggeredcardtemplate.o: miniontriggeredcardtemplate.cc miniontriggeredcardtemplate.h \
		cardtemplate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o miniontriggeredcardtemplate.o miniontriggeredcardtemplate.cc

minionactivatedcardtemplate.o: minionactivatedcardtemplate.cc minionactivatedcardtemplate.h \
		cardtemplate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minionactivatedcardtemplate.o minionactivatedcardtemplate.cc

enchantmentcardtemplate.o: enchantmentcardtemplate.cc enchantmentcardtemplate.h \
		cardtemplate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o enchantmentcardtemplate.o enchantmentcardtemplate.cc

enchantmentadcardtemplate.o: enchantmentadcardtemplate.cc enchantmentadcardtemplate.h \
		cardtemplate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o enchantmentadcardtemplate.o enchantmentadcardtemplate.cc

spellcardtemplate.o: spellcardtemplate.cc spellcardtemplate.h \
		cardtemplate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o spellcardtemplate.o spellcardtemplate.cc

ritualcardtemplate.o: ritualcardtemplate.cc ritualcardtemplate.h \
		cardtemplate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ritualcardtemplate.o ritualcardtemplate.cc

moc_canvas.o: moc_canvas.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_canvas.o moc_canvas.cc

moc_cardtemplate.o: moc_cardtemplate.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cardtemplate.o moc_cardtemplate.cc

moc_playercardtemplate.o: moc_playercardtemplate.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_playercardtemplate.o moc_playercardtemplate.cc

moc_centercardtemplate.o: moc_centercardtemplate.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_centercardtemplate.o moc_centercardtemplate.cc

moc_minioncardtemplate.o: moc_minioncardtemplate.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_minioncardtemplate.o moc_minioncardtemplate.cc

moc_miniontriggeredcardtemplate.o: moc_miniontriggeredcardtemplate.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_miniontriggeredcardtemplate.o moc_miniontriggeredcardtemplate.cc

moc_minionactivatedcardtemplate.o: moc_minionactivatedcardtemplate.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_minionactivatedcardtemplate.o moc_minionactivatedcardtemplate.cc

moc_enchantmentcardtemplate.o: moc_enchantmentcardtemplate.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_enchantmentcardtemplate.o moc_enchantmentcardtemplate.cc

moc_enchantmentadcardtemplate.o: moc_enchantmentadcardtemplate.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_enchantmentadcardtemplate.o moc_enchantmentadcardtemplate.cc

moc_spellcardtemplate.o: moc_spellcardtemplate.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_spellcardtemplate.o moc_spellcardtemplate.cc

moc_ritualcardtemplate.o: moc_ritualcardtemplate.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ritualcardtemplate.o moc_ritualcardtemplate.cc

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

